### ISSUE TITLE
Simplify: Apply shared properties to multiple elements at once rather than individually.

### ISSUE THREAD

**Issue by josephtkim** [Galentinoeh/prj-rev-bwfs-dasmoto#5]
Similar to how you applied the font-family property to the entire page, it is a good idea to simplify the code for other shared properties, like the font-weight. You might apply this like so

```css
h1, h3, h4, .highlight {
  font-weight: bold;
}
```
